### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by vitormattos** [celorodovalho/phpdfbot#5]
Criação de arquivo contributing com instruções de como contribuir

**Comment by celorodovalho** [comment]
#6

**Comment by celorodovalho** [comment]
### Message:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select * from `opportunities` where `0` = id and `1` = < and `2` = 5 and `opportunities`.`deleted_at` is null)
```

### File/Line:
```
/home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Connection.php::664
```

### Code:
```php
42S22
```

### Trace:
```php
#0 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2130): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2118): Illuminate\Database\Query\Builder->runSelect()
#4 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2604): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2119): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\Database\Query\Builder->get(Array)
#7 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(505): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 /home/marcelo/Workspace/phpdfbot/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php(543): Illuminate\Database\Eloquent\Builder->get(Array)
#9 /home/marcelo/Workspace/phpdfbot/app/Console/Commands/BotPopulateChannel.php(113): Prettus\Repository\Eloquent\BaseRepository->findWhere(Array)
#10 [internal function]: App\Console\Commands\BotPopulateChannel->handle()
#11 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#12 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#16 /home/marcelo/Workspace/phpdfbot/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /home/marcelo/Workspace/phpdfbot/vendor/symfony/console/Application.php(1011): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/marcelo/Workspace/phpdfbot/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\BotPopulateChannel), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/marcelo/Workspace/phpdfbot/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/marcelo/Workspace/phpdfbot/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
```

### Log:
```php
https://dev.marcelorodovalho.com/workspace/phpdfbot/storage/app/logs/1579457381.log
```
