### ISSUE TITLE
include(/home/marcelo/Workspace/phpdfbot/vendor/composer/../../app/Contracts/CollectInterface.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by celorodovalho** [celorodovalho/phpdfbot#59]
### Message:
```
include(/home/marcelo/Workspace/phpdfbot/vendor/composer/../../app/Contracts/CollectInterface.php): failed to open stream: No such file or directory
```

### File/Line:
```
/home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php::444
```

### Code:
```php
0
```

### Trace:
```php
#0 /home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/home/m...', '/home/marcelo/W...', 444, Array)
#1 /home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php(444): include()
#2 /home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/marcelo/W...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Contracts\\C...')
#4 [internal function]: spl_autoload_call('App\\Contracts\\C...')
#5 /home/marcelo/Workspace/phpdfbot/app/Helpers/Helper.php(56): class_implements('App\\Contracts\\C...')
#6 /home/marcelo/Workspace/phpdfbot/app/Console/Commands/BotPopulateChannel.php(89): App\Helpers\Helper::getImplementations('App\\Contracts\\C...')
#7 [internal function]: App\Console\Commands\BotPopulateChannel->__construct(Object(Telegram\Bot\BotsManager))
#8 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(825): ReflectionClass->newInstanceArgs(Array)
#9 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('App\\Console\\Com...')
#10 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('App\\Console\\Com...', Array)
#11 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('App\\Console\\Com...', Array)
#12 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(258): Illuminate\Foundation\Application->make('App\\Console\\Com...')
#13 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(244): Illuminate\Console\Application->resolve('App\\Console\\Com...')
#14 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(149): Illuminate\Foundation\Console\Kernel->Illuminate\Foundation\Console\{closure}(Object(Illuminate\Console\Application))
#15 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(72): Illuminate\Console\Application->bootstrap()
#16 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(342): Illuminate\Console\Application->__construct(Object(Illuminate\Foundation\Application), Object(Illuminate\Events\Dispatcher), '5.8.36')
#17 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\Foundation\Console\Kernel->getArtisan()
#18 /home/marcelo/Workspace/phpdfbot/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}
```

### Log:
```php
https://dev.marcelorodovalho.com/workspace/phpdfbot/storage/app/logs/1579435802.log
```

**Comment by celorodovalho** [comment]
### Message:
```
include(/home/marcelo/Workspace/phpdfbot/vendor/composer/../../app/Contracts/CollectInterface.php): failed to open stream: No such file or directory
```

### File/Line:
```
/home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php::444
```

### Code:
```php
0
```

### Trace:
```php
#0 /home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/home/m...', '/home/marcelo/W...', 444, Array)
#1 /home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php(444): include()
#2 /home/marcelo/Workspace/phpdfbot/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/marcelo/W...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Contracts\\C...')
#4 [internal function]: spl_autoload_call('App\\Contracts\\C...')
#5 /home/marcelo/Workspace/phpdfbot/app/Helpers/Helper.php(56): class_implements('App\\Contracts\\C...')
#6 /home/marcelo/Workspace/phpdfbot/app/Console/Commands/BotPopulateChannel.php(89): App\Helpers\Helper::getImplementations('App\\Contracts\\C...')
#7 [internal function]: App\Console\Commands\BotPopulateChannel->__construct(Object(Telegram\Bot\BotsManager))
#8 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(825): ReflectionClass->newInstanceArgs(Array)
#9 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('App\\Console\\Com...')
#10 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('App\\Console\\Com...', Array)
#11 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('App\\Console\\Com...', Array)
#12 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(258): Illuminate\Foundation\Application->make('App\\Console\\Com...')
#13 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(244): Illuminate\Console\Application->resolve('App\\Console\\Com...')
#14 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(149): Illuminate\Foundation\Console\Kernel->Illuminate\Foundation\Console\{closure}(Object(Illuminate\Console\Application))
#15 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Console/Application.php(72): Illuminate\Console\Application->bootstrap()
#16 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(342): Illuminate\Console\Application->__construct(Object(Illuminate\Foundation\Application), Object(Illuminate\Events\Dispatcher), '5.8.36')
#17 /home/marcelo/Workspace/phpdfbot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\Foundation\Console\Kernel->getArtisan()
#18 /home/marcelo/Workspace/phpdfbot/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main}
```

### Log:
```php
https://dev.marcelorodovalho.com/workspace/phpdfbot/storage/app/logs/1579435804.log
```
